---
title: "Untitled"
author: "Michael Samuel"
date: "10/22/2019"
output: html_document
params: 
  county: "Solano"
fontsize: 40pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(dplyr)
library(readr)
library(readxl)
library(ggplot2)
library(fs)
```


```{r}
topN <- 20
```


```{r}
myPlace           <- "f:/0.CBD/myCBD/"
secure.location   <- secure.location  <- "H:/0.Secure.Data/"


oshpd_subset      <- readRDS(file=path(secure.location, "myData/oshpd_subset.rds")) 
ccsLink           <- read_csv("f:/0.CBD/myCBD/myInfo/ccs_code_to_name_link.csv") %>%
                       mutate(ccs_diagP = as.character(ccs_diagP))

coMap             <- as.data.frame(read_excel(paste0(myPlace,"/myInfo/County Codes to County Names Linkage.xlsx")))

PDDwork           <- full_join(oshpd_subset,ccsLink,by="ccs_diagP")  %>%
                       left_join(coMap,by = c("patcnty"= "cdphcaCountyTxt"))

PDDwork           <- bind_rows(PDDwork, mutate(PDDwork,countyName = "CALIFORNIA"))

tTab              <- PDDwork %>% group_by(countyName,ccsName)  %>% summarize(nHosp = n()) %>%
                       filter(nHosp > 20)

tCode  <- read_csv("f:/0.CBD/myCBD/myInfo/ccs_code_to_name_link.csv") 

tTabnoPreg <- left_join(tTab,ccsLink,by="ccsName")  %>% 
                filter(!(ccs_diagP %in% c(218, 195, 193, 185, 189, 181, 191, 183))) %>%
                select(-ccs_diagP)








```



```{r}
# FOR BURDEN VIEW
write_csv(tTabnoPreg, "f:/BurdenView/Data/OSHPD/Hospital_Discharge_CCS_grouping_2016.csv")
```


### CCS exploration - 10/22/2019

### Bar charts of top 20 primarly code reason for hospitalization for California overall in 2016. Condition groupings based on the ["Clinical Classifications Software" system]( https://www.hcup-us.ahrq.gov/toolssoftware/ccsr/ccs_refined.jsp). First chart, all conditions. Second chart, excluding all birth and pregnancy-related conditions. 


<br>

```{r}

wDat <- filter(tTab,countyName==params$county) %>% arrange(desc(nHosp)) 
xDat <- wDat %>%   top_n(topN,nHosp)

ggplot(xDat, aes(x=reorder(ccsName,nHosp),y=nHosp)) + 
             geom_bar(stat="identity") + 
             coord_flip() +
             labs(title=paste0("CCS Codes 2016, ",params$county),
                  x="") +
             theme(plot.title = element_text(color = "blue", size = 10, face = "bold")) 


tCode  <- read_csv("f:/0.CBD/myCBD/myInfo/ccs_code_to_name_link.csv") 
wDat   <- left_join(wDat,tCode,by="ccsName") %>% filter(!(ccs_diagP %in% c(218, 195, 193, 185, 189, 181, 191, 183))) %>%                    arrange(desc(nHosp))

xDat   <-  top_n(wDat,topN,nHosp)

ggplot(xDat, aes(x=reorder(ccsName,nHosp),y=nHosp)) + 
             geom_bar(stat="identity") + 
             coord_flip() +
             labs(title=paste0("CCS Codes 2016, ",params$county,"\nexcluding pregnancy-related"),x="") +
             theme(plot.title = element_text(color = "blue", size = 10, face = "bold"))

```

