---
title: "Race Work"
author: "Michael Samuel"
date: "January 28, 2019"
always_allow_html: yes
output:
  html_document: default
  word_document: default
---
```{r echo=FALSE, message=FALSE}

#-- Load Packages ------------------------------------------------------------
 library(ggplot2)
 library(dplyr)
 library(tidyr)
 library(readxl)
 library(readr) 
 library(fs)
 library(markdown)

#-- Key Constants -----------------------------------------------------------

 whichData <- "real"
 myPlace   <- "f:/0.CBD/myCBD"
 STATE     <- "CALIFORNIA"
 yearGrp   <- "2013-2017"

 datCounty    <- readRDS(path(myPlace,"/myData/",whichData,"datCounty.RDS"))
 datCounty.RE <- readRDS(path(myPlace,"/myData/",whichData,"datCounty_RE.RDS"))
 
# CHANGE CODES EVERYWHWERE  !!! no -
#         c("White-NH","Black-NH","AIAN-NH","Asian-NH","NHPI-NH", "Multi-NH","Hisp")
tRace <-  c("White-NH","Black-NH",          "Asian-NH",                      "Hisp")

```



```{r echo=FALSE, message=FALSE }
  gbdMap0    <- as.data.frame(read_excel( path(myPlace,"myInfo//gbd.ICD.Map.xlsx/"), sheet="main")) 

fullCauseList       <- gbdMap0[!is.na(gbdMap0$causeList),c("LABEL","nameOnly")] %>% arrange(LABEL)

```





```{r echo=FALSE, message=FALSE }

.t.00 <- datCounty.RE %>% filter(county==STATE,yearG3 == "2015-2017",Level=="lev2",
                              !(raceCode %in% c("Multi-NH")) )  
                            #  !(raceCode %in% c("AIAN-NH","NHPI-NH","Multi-NH")) ) 

.t.0 <-  .t.00 %>% filter(sex == "Total")  


t.2 <- .t.0 %>%  select(CAUSE,Ndeaths,raceCode) %>%          # N BY RACE + N RANK  (8)
            spread(key=raceCode,value=Ndeaths) 



t.3 <- .t.0 %>%  select(CAUSE,aRate,raceCode) %>%           # ADJUSTED RATE BY RACE + RANK + RATIO (12)
            spread(key=raceCode,value=aRate) %>%
            mutate(AsianRank = round(rank(-`Asian-NH`)),
                   BlackRank = round(rank(-`Black-NH`)),
                   HispRank  = round(rank(-`Hisp`)),
                   WhiteRank = round(rank(-`White-NH`)),
                   NatAmRank = round(rank(-`AIAN-NH`)),
                   HawaiiPI  = round(rank(-`NHPI-NH`)))


t.5      <- bind_cols(t.2,t.3) 
CAUSE    <- t.5 %>% select(CAUSE)
t.workA  <- right_join(fullCauseList,t.5,by=c("LABEL"="CAUSE")) %>%
              select(-LABEL,-CAUSE1)

write_csv(t.workA,"raceWorkNATIVEAMExplore.csv", na ="")



```

