---
title: "Race Work"
author: "Michael Samuel"
date: "January 28, 2019"
always_allow_html: yes
output:
  word_document: default
  html_document: default
---
```{r echo=FALSE, message=FALSE}

#-- Load Packages ------------------------------------------------------------
 library(ggplot2)
 library(dplyr)
 library(tidyr)
 library(readxl)
 library(readr) 
 library(fs)
 library(markdown)

#-- Key Constants -----------------------------------------------------------

 whichData <- "real"
 myPlace   <- "E:/0.CBD/myCBD"
 STATE     <- "CALIFORNIA"
 yearGrp   <- "2013-2017"

 datCounty    <- readRDS(path(myPlace,"/myData/",whichData,"datCounty.RDS"))
 datCounty.RE <- readRDS(path(myPlace,"/myData/",whichData,"datCounty.RE.RDS"))
 
# CHANGE CODES EVERYWHWERE  !!! no -
#         c("White-NH","Black-NH","AIAN-NH","Asian-NH","NHPI-NH", "Multi-NH","Hisp")
tRace <-  c("White-NH","Black-NH",          "Asian-NH",                      "Hisp")
tRace  <- c("White-NH","Black-NH","AIAN-NH","Asian-NH","NHPI-NH",            "Hisp")

```



### *Kidney Disease...

```{r echo=FALSE, message=FALSE}
  t.K <- datCounty.RE %>% filter(county==STATE,CAUSE=="D10",sex=="Total",raceCode %in% tRace)
 
 # note that size in not in the aes() part...
x <-  ggplot(data=t.K, aes(x=yearG3, y=aRate, group=raceCode)) +
      geom_line(aes(color=raceCode),size=1.5) +
      ggtitle("KIDNEY DISEASE - Age-Adjusted Death Rate") 
x 

x +  scale_y_continuous(trans='log2') + ggtitle("LOG SCALE KIDNEY DISEASE - Age-Adjusted Death Rate")
 
 
```


