# =============================================================================
# "server.R" file     
#
# required file for Shiny Application
#
# renders all visual object (maps, charts, help boxes)
# modifies inputs through interativity 
#  
# Michael Samuel
# 2018
#
# =============================================================================

shinyServer(function(input, output,session) {

# IHME WORK (TEMP) ########################  
  #source(paste0(myPlace,"/IHMEwork/arrows_Server.Part.R"))
  
  output$network <- renderVisNetwork({
    nodes_and_edges <- create_nodes(input$levelX, input$measureX, input$sexX, input$metricX,
                                    input$yearX[1], input$yearX[2], input$displayX)
                                    nodes <- nodes_and_edges$nodes
    edges <- nodes_and_edges$edges
    vis_network(nodes, edges, input$displayX)
  })
  
  
# -------------------------------------------------------------------------------  

# "onclick" is a function from shinyjs package
# used here to move to specified tab when specified image in clicked
# first perameter is id associated with images from home page main pannel
#  see ui.R  "tabPanel("Home Page"..."
shinyjs::onclick("map1I",     updateTabsetPanel(session,inputId="ID",selected="22"))  
shinyjs::onclick("map2I",     updateTabsetPanel(session,inputId="ID",selected="23"))  
shinyjs::onclick("rankcauseI",updateTabsetPanel(session,inputId="ID",selected="33"))  
shinyjs::onclick("ranktableI",updateTabsetPanel(session,inputId="ID",selected="45"))  
shinyjs::onclick("rankgeoI",  updateTabsetPanel(session,inputId="ID",selected="44"))  
shinyjs::onclick("trendI",    updateTabsetPanel(session,inputId="ID",selected="55"))  
shinyjs::onclick("scatterI",  updateTabsetPanel(session,inputId="ID",selected="66"))  
  
# -------------------------------------------------------------------------------  

# function used below as "shortcut" for formating each Modal
myModal <- function(whatInfo) {
  showModal(modalDialog(HTML(whatInfo),
            easyClose = TRUE,
            footer = modalButton("Close")
))}

# generates help "objects" used for "drop down" help buttons
# single argument to each HTML function is a text object (vector of length 1) 
#   generated by source("...AppText.txt) in Global.R
observeEvent(input$causeHelp,     {myModal(causeHelp)})
observeEvent(input$cutmethodHelp, {myModal(cutmethodHelp)})
observeEvent(input$statecutHelp,  {myModal(stateCutHelp)})
observeEvent(input$measureHelp,   {myModal(measureHelp)})
observeEvent(input$levelHelp,     {myModal(levelHelp)})



# generates help "objects" used for tab help buttons, as above
observeEvent(input$mapTab,            {myModal(mapTab)})
observeEvent(input$conditionTab,      {myModal(conditionTab)})
observeEvent(input$conditionTableTab, {myModal(conditionTableTab)})
observeEvent(input$conditionSexTab,   {myModal(conditionSexTab)})
observeEvent(input$rankGeoTab,        {myModal(rankGeoTab)})
observeEvent(input$trendTab,          {myModal(trendTab)})
observeEvent(input$sdohTab,           {myModal(sdohTab) })

# generates text "object" used for news you can use buttons, from "...newsUseText.txt" as above
observeEvent(input$newsUse,           {myModal(newsUse)})

# -------------------------------------------------------------------------------  

# create "empty" reactive value
#  then fill it with current "myCause" selection for use elsewhere
current_Cause <- reactiveVal(NULL)
observeEvent(input$myCAUSE, { current_Cause(input$myCAUSE) })

# change "myCause" list based on geographic level selected, and specifiy current
#   selection if Community or County level
observeEvent(input$myGeo, {
    if(input$myGeo=="Census Tract"){updateSelectInput(session, "myCAUSE", choices = bigCode ) }
    if(input$myGeo=="Community")   {updateSelectInput(session, "myCAUSE", choices = phCode, selected=current_Cause()) } 
    if(input$myGeo=="County")      {updateSelectInput(session, "myCAUSE", choices = fullList,selected=current_Cause()  ) }
})



# if myLHJ is not STATE (e.g. "CALIFORNIA"), then myGeo is "Community" so
#  that county map will not show just overall county data

observeEvent(input$myLHJ, {
  if(input$myLHJ != STATE & input$ID %in% c(22,23)){updateSelectInput(session, "myGeo", selected = "Community") }
})

observeEvent(input$ID, {
  if(input$myLHJ != STATE & input$ID %in% c(22,23)){updateSelectInput(session, "myGeo", selected = "Community") }
})






# Hard wire... Trend only COUNTY for now
observeEvent(input$ID,{
  if(input$ID %in% c(55) ) 
  {updateSelectInput(session, "myCAUSE", choices = fullList,selected=current_Cause()  )}
})
    

observeEvent(input$ID,{
  if(input$ID %in% c(44,56,57) &  input$myGeo=="Community") 
  {updateSelectInput(session, "myCAUSE", choices = phCode,selected=current_Cause()  )}
})



observeEvent(input$ID,{
  if(input$ID %in% c(22,23)  & input$myGeo=="Census Tract" ) 
  {updateSelectInput(session, "myCAUSE", choices = bigCode )}
})






# not used now, but saved as examples of other reactivity
# observeEvent(input$ID,{
#  if(input$ID %in% c(33,34,44,45,55)) 
#   {updateSelectInput(session, "myLHJ", choices = lList, selected=current_LHJ())}
#  if(input$ID %in% c(22,23)  & current_LHJ() != "CALIFORNIA") 
#   {updateSelectInput(session, "myLHJ", choices = lListNoState, selected=current_LHJ())}
#  if(input$ID %in% c(22,23)  & current_LHJ() == "CALIFORNIA") 
#   {updateSelectInput(session, "cZoom", selected=FALSE) }
#   
# )
#for two input use:
# observeEvent(input$test1 | input$test2, {
#    if(input$test1==0 && input$test2==0){







#--------------------------------------------------------------------------------
# Render Application Maps and Charts --------------------------------------------



output$cbdMapTL     <- renderLeaflet(cbdMapXLeaf(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex,input$myStateCut, input$myGeo, input$myLabName, input$myCutSystem))


# ALL HELL BREAKS LOOSE WITH dbounce
# use dbounce() below to "delay" rendering of may to avoid temporary error
# output$cbdMapTL     <- debounce(renderLeaflet(cbdMapXLeaf(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex,input$myStateCut, input$myGeo, input$myLabName, input$myCutSystem)),2000)




 #  mapJunk          <- cbdMapXLeaf(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex,input$myStateCut, input$myGeo, input$myLabName, input$myCutSystem)

#  output$cbdMapTL   <- renderLeaflet(mapJunk)


output$mapFigureI <- downloadHandler(filename=function(){paste0("MAP2",".png")},content = function(file) {
  png(file, width = 10, height = 7, units = "in", pointsize = 10,res=100)
  print(cbdMapXLeaf(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex,input$myStateCut, input$myGeo, input$myLabName, input$myCutSystem))
  dev.off()
})




output$mapFigure <- downloadHandler(filename=function(){paste0("MAP",".png")},content = function(file) {
  png(file, width = 10, height = 7, units = "in", pointsize = 10,res=100)
  print(cbdMapXStat(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex,input$myStateCut, input$myGeo, input$myLabName, input$myCutSystem))
  dev.off()
})


output$rankCauseFigure <- downloadHandler(filename=function(){paste0("CAUSE",".png")},content = function(file) {
  png(file, width = 10, height = 7, units = "in", pointsize = 10,res=100)
  print(rankCause(input$myLHJ,                input$myMeasureShort, input$myYear, input$mySex, input$myLev, input$myN))
  dev.off()
})


output$cbdMapTS     <- renderPlot(   cbdMapXStat(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex,input$myStateCut, input$myGeo, input$myLabName, input$myCutSystem))


output$rankCause    <- renderPlot(     rankCause(input$myLHJ,                input$myMeasureShort,  input$mySex, input$myLev, input$myN,input$myYear))
output$rankCauseSex <- renderPlot(  rankCauseSex(input$myLHJ,                input$myMeasure     , input$myYear,              input$myLev, input$myN))
output$rankGeo      <- renderPlot(       rankGeo(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex, input$myCI,input$myRefLine))

output$trend        <- renderPlot(         trend(input$myLHJ, input$myCAUSE, input$myMeasure, input$myYearGrouping))
#output$trend        <- renderPlotly(         trend(input$myLHJ, input$myCAUSE, input$myMeasure))



output$trendRace    <- renderPlot(         trendRace(input$myLHJ, input$myCAUSE, input$myMeasure,input$myLogTrans))


output$trendEducation    <- renderPlot(         trendEducation(input$myLHJ, input$myCAUSE, input$mySex,input$myMeasure,input$myLogTrans))



# output$OSHPD1    <- renderPlot(         oshpdPlot1(input$myLHJ, input$myOSHPDtype, input$mySex, input$myN))
output$OSHPD1    <- renderPlot(         oshpdPlot1(input$myLHJ, input$myOSHPDtype, input$mySex, input$myN, input$myVar))

output$OSHPD2    <- renderPlotly(         oshpdPlot2(input$myLHJ, input$myOSHPDtype, input$mySex, input$myN, input$myVar))


output$mdcdrg   <- renderPlot(mdc_drg_plot(input$myLHJ, input$myOSHPDtype_mdcdrg, input$mySex, input$myN, input$myVar))

output$scatter      <- renderPlotly( scatterSDOH(             input$myCAUSE, input$myMeasure,                    input$mySex,                  input$myGeo,input$myX))

output$rankCauseT   <- renderDataTable(rankCauseTab(input$myLHJ, input$myYear, input$mySex),
                                     option=list(columnDefs=list(list(targets=3:5, class="dt-right")), pageLength = 60)) #DT::


# Generate labels and titles for maps and charts --------------------------------

sexLabel   <- renderText({if (input$mySex == "Total")  sexLabel  <- ""      else sexLabel  <- paste0(", among ",input$mySex,"s")})
geoLabel   <- renderText({if (input$myLHJ==STATE)      geoLab    <- ""      else geoLab    <- paste0(" in ",input$myLHJ)})
timeLabel  <- renderText({if (input$myGeo != "County") timeLabel <- yearGrp else timeLabel <- paste(input$myYear)})

output$map_title <- renderUI({h4(strong(
                    HTML(paste0(   deathMeasuresNames[deathMeasures == input$myMeasure],
                                   " from ",
                                   fullCauseList[fullCauseList[,"LABEL"]==input$myCAUSE,"nameOnly"][1],     # FIX this [1] here now since second element is NA
                                   " in ",span(timeLabel(),style="color:blue"),
                                   " by ",input$myGeo,
                                   sexLabel(), geoLabel(),
                                   sep = " ")))) })

# END of shinyServer ---------------------------------------------------------

}) 

# -- END ----------------------------------------------------------------------


# previously needed - keeping just in case....
#yearGrp <- "2013-2017"   # why doesn't it find this from global?