# =============================================================================
# "server.R" file     
#
# required file for Shiny Application
#
# renders all visual object (maps, charts, help boxes)
# modifies inputs through interativity 
#  
# Michael Samuel
# 2018
#
# =============================================================================

shinyServer(function(input, output,session) {

# -------------------------------------------------------------------------------  

  # "onclick" is a function from shinyjs package
# used here to move to specified tab when specified image in clicked
# first perameter is id associated with images from home page main pannel
#  see ui.R  "tabPanel("Home Page"..."
shinyjs::onclick("map1I",     updateTabsetPanel(session,inputId="ID",selected="22"))  
shinyjs::onclick("map2I",     updateTabsetPanel(session,inputId="ID",selected="23"))  
shinyjs::onclick("rankcauseI",updateTabsetPanel(session,inputId="ID",selected="33"))  
shinyjs::onclick("ranktableI",updateTabsetPanel(session,inputId="ID",selected="45"))  
shinyjs::onclick("rankgeoI",  updateTabsetPanel(session,inputId="ID",selected="44"))  
shinyjs::onclick("trendI",    updateTabsetPanel(session,inputId="ID",selected="55"))  
shinyjs::onclick("scatterI",  updateTabsetPanel(session,inputId="ID",selected="66"))  
  
# -------------------------------------------------------------------------------  

# generates help "objects" used for "drop down" help buttons
# single argument to each HTML function is a text object (vector of length 1) 
#   generated by source("...AppText.txt) in Global.R
observeEvent(input$causeHelp,     {showModal(modalDialog(HTML(causeHelp),     easyClose = TRUE))})
observeEvent(input$cutmethodHelp, {showModal(modalDialog(HTML(cutmethodHelp), easyClose = TRUE))})
observeEvent(input$statecutHelp,  {showModal(modalDialog(HTML(stateCutHelp),  easyClose = TRUE))})
observeEvent(input$measureHelp,   {showModal(modalDialog(HTML(measureHelp),   easyClose = TRUE))})

# generates help "objects" used for tab help buttons, as above
observeEvent(input$mapTab,            {showModal(modalDialog(HTML(mapTab),            easyClose = TRUE))})
observeEvent(input$conditionTab,      {showModal(modalDialog(HTML(conditionTab),      easyClose = TRUE))})
observeEvent(input$conditionTableTab, {showModal(modalDialog(HTML(conditionTableTab), easyClose = TRUE))})
observeEvent(input$conditionSexTab,   {showModal(modalDialog(HTML(conditionSexTab),   easyClose = TRUE))})
observeEvent(input$rankGeoTab,        {showModal(modalDialog(HTML(rankGeoTab),        easyClose = TRUE))})
observeEvent(input$trendTab,          {showModal(modalDialog(HTML(trendTab),          easyClose = TRUE))})
observeEvent(input$sdohTab,           {showModal(modalDialog(HTML(sdohTab),           easyClose = TRUE))})

# generates text "object" used for news you can use buttons, from "...newsUseText.txt" as above
observeEvent(input$newsUse,           {showModal(modalDialog(HTML(newsUse),           easyClose = TRUE))})

# -------------------------------------------------------------------------------  

# create "empty" reactive value
#  then fill it with current "myCause" selection for use elsewhere
current_Cause <- reactiveVal(NULL)
observeEvent(input$myCAUSE, { current_Cause(input$myCAUSE) })

# change "myCause" list based on geographic level selected, and specifiy current
#   selection if Community or County level
observeEvent(input$myGeo, {
    if(input$myGeo=="Census Tract"){updateSelectInput(session, "myCAUSE", choices = bigCode ) }
    if(input$myGeo=="Community")   {updateSelectInput(session, "myCAUSE", choices = phCode, selected=current_Cause()) } 
    if(input$myGeo=="County")      {updateSelectInput(session, "myCAUSE", choices = causeNum36,selected=current_Cause()  ) }
})


# if myLHJ is not STATE (e.g. "CALIFORNIA"), then myGeo is "Community" so
#  that county map will not show just overall county data
observeEvent(input$myLHJ, {
  if(input$myLHJ != STATE){updateSelectInput(session, "myGeo", selected = "Community") }
})

# not used now, but saved as examples of other reactivity
# observeEvent(input$ID,{
#  if(input$ID %in% c(33,34,44,45,55)) 
#   {updateSelectInput(session, "myLHJ", choices = lList, selected=current_LHJ())}
#  if(input$ID %in% c(22,23)  & current_LHJ() != "CALIFORNIA") 
#   {updateSelectInput(session, "myLHJ", choices = lListNoState, selected=current_LHJ())}
#  if(input$ID %in% c(22,23)  & current_LHJ() == "CALIFORNIA") 
#   {updateSelectInput(session, "cZoom", selected=FALSE) }
#   
# )
#for two input use:
# observeEvent(input$test1 | input$test2, {
#    if(input$test1==0 && input$test2==0){

#--------------------------------------------------------------------------------
# Render Application Maps and Charts --------------------------------------------

output$cbdMapTL     <- renderLeaflet(cbdMapXLeaf(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex,input$myStateCut, input$myGeo, input$myLabName, input$myCutSystem))
output$cbdMapTS     <- renderPlot(   cbdMapXStat(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex,input$myStateCut, input$myGeo, input$myLabName, input$myCutSystem))
output$rankCause    <- renderPlot(     rankCause(input$myLHJ,                input$myMeasureShort, input$myYear, input$mySex, input$myLev, input$myN))
output$rankCauseSex <- renderPlot(  rankCauseSex(input$myLHJ,                input$myMeasure     , input$myYear,              input$myLev, input$myN))
output$rankGeo      <- renderPlot(       rankGeo(input$myLHJ, input$myCAUSE, input$myMeasure,      input$myYear, input$mySex, input$myCI,input$myRefLine))
output$trend        <- renderPlot(         trend(input$myLHJ, input$myCAUSE, input$myMeasure))
output$scatter      <- renderPlotly( scatterSDOH(             input$myCAUSE, input$myMeasure,                    input$mySex,                  input$myGeo,input$myX))

output$rankCauseT   <- renderDataTable(rankCauseTab(input$myLHJ, input$myYear, input$mySex),
                                     option=list(columnDefs=list(list(targets=3:5, class="dt-right")), pageLength = 60)) #DT::


# Generate labels and titles for maps and charts --------------------------------

sexLabel   <- renderText({if (input$mySex == "Total")  sexLabel  <- ""      else sexLabel  <- paste0(", among ",input$mySex,"s")})
geoLabel   <- renderText({if (input$myLHJ==STATE)      geoLab    <- ""      else geoLab    <- paste0(" in ",input$myLHJ)})
timeLabel  <- renderText({if (input$myGeo != "County") timeLabel <- yearGrp else timeLabel <- paste(input$myYear)})

output$map_title <- renderUI({h4(strong(
                    HTML(paste0(   lMeasuresC[lMeasures == input$myMeasure],
                                   " from ",
                                   fullCauseList[fullCauseList[,"LABEL"]==input$myCAUSE,"nameOnly"][1],     # FIX this [1] here now since second element is NA
                                   " in ",span(timeLabel(),style="color:blue"),
                                   " by ",input$myGeo,
                                   sexLabel(), geoLabel(),
                                   sep = " ")))) })

# END of shinyServer ---------------------------------------------------------

}) 

# -- END ----------------------------------------------------------------------


# previously needed - keeping just in case....
#yearGrp <- "2013-2017"   # why doesn't it find this from global?