---
title: "Untitled"
author: "Michael Samuel"
date: "9/26/2019"
output:
  html_document: default
  word_document: default
params:
  county: Trinity
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE, warning = FALSE)
```

```{r}
library(sf)
library(fs)
library(tmap)
library(dplyr)
library(readr)
library(kableExtra)
library(DT)
library(ggplot2)

myDrive <- "F:/0.CBD"  
myPlace <- paste0(myDrive,"/myCBD") 
upPlace <- paste0(myDrive,"/myUpstream") 
upGuns  <- paste0(myDrive,"/myAnalyses/FireArms") 

datComm            <- readRDS(path(upGuns,"datComm.RDS"))
datCounty_5year    <- readRDS(path(upGuns,"datCounty_5year.RDS"))
datCounty_RE       <- readRDS(path(upGuns,"datCounty_RE.RDS"))


geocodeFactor  <- read_csv(paste0(myPlace,"/myInfo/geocodeFactor.csv"))


```


```{r}
datComm0    <- datComm %>% filter(CAUSE %in% c("S","S1","S2","S3","S4","S5")) %>%
                         mutate(causeName = ifelse(CAUSE=="S","ALL Firearm",causeName)) %>%
                         select(causeName, CAUSE, sex,county,comName,comID,Ndeaths,cDeathRate,aRate,aLCI,aUCI,aSE)

datCounty1  <- datCounty_5year %>% filter(CAUSE %in% c("S","S1","S2","S3","S4","S5"),yearG5=="2014-2018") %>%
                         mutate(causeName = ifelse(CAUSE=="S","ALL Firearm",causeName)) %>%
                         select(causeName,sex,county,Ndeaths,cDeathRate,aRate,aLCI,aUCI)

datState1  <- datCounty_5year %>% filter(CAUSE %in% c("S","S1","S2","S3","S4","S5"),county=="CALIFORNIA",yearG5=="2014-2018") %>%
                         mutate(causeName = ifelse(CAUSE=="S","ALL Firearm",causeName)) %>%
                         mutate(aRateState = aRate,aSEState=aSE) %>%
                         select(sex,causeName,CAUSE,Ndeaths,aRateState,aSEState)




```


```{r}
datComm1   <- left_join(datComm0,select(datState1,-causeName,-Ndeaths),by=c("sex","CAUSE")) %>%
              left_join(geocodeFactor,by="county") %>% 
                       #   mutate(aRate = aRate / percentGeocoded) %>%
                           mutate(myZ    = (aRate-aRateState) / sqrt(aSE^2 + aSEState^2)) %>%
                           mutate(sig    = ifelse(myZ>1.96, 1, ifelse(myZ < -1.96,3,2)),
                                  pValue = 1-pnorm(myZ))

```




```{r}
stateTab <- datState1  %>% filter(CAUSE %in% c("S","S2","S3"),sex=="Total") %>% select(-CAUSE)




```









```{r}

 datatable(datCounty1, rownames = FALSE,filter = 'top',options = list(pageLength=60) )
 
 # %>%
 #     formatRound(columns=temp[c(2:7)], digits=0) %>%
 #     formatRound(columns=temp[c(8:13,17:20)], digits=1) %>%
 #     formatRound(columns=temp[c(14)], digits=2) %>%
 #     formatRound(columns=temp[c(15)], digits=3) %>% 
 #     formatStyle(columns=temp[c(4,7)],backgroundColor = 'lightblue') %>%
 #     formatStyle(columns=temp[c(10,13)],backgroundColor = 'gray') %>%
 #     formatStyle(columns=temp[c(15)],backgroundColor = styleInterval(brks, clrs))  
  

write.csv(datCounty1,"firearms-county.csv")

```


```{r}

brks <- c(-0.1,0.01,.05,0.95,0.99,1.1)
brks <- c(0.01,.05,0.95,0.99)

clrs <- c("red","pink","white","blue","green")

tTab <- datComm1 %>% select(-comID,-cDeathRate,-CAUSE,-aSE,-aSEState,-myZ)

 datatable(tTab, rownames = FALSE,filter = 'top',options = list(pageLength=60) )  %>%
   formatRound(columns="pValue",digits=4)  %>%    
   formatStyle(columns="pValue",backgroundColor = styleInterval(brks, clrs)) %>%
   formatStyle(columns="aRate",backgroundColor = 'lightblue') %>%
   formatStyle(columns="aRateState",backgroundColor = 'lightgreen')

                
write.csv(datComm1,"firearms-MSSA.csv")


```




```{r}
shape_Comm  <- st_read(path(myPlace,"/myData/shape_Comm.shp"),stringsAsFactors=FALSE)
samVec      <- c(1,1.9,2.9,3)

```


```{r}

myCause  <- c("Firearm-Suicide","Firearm-Homicide")
myCause  <- "Firearm-Homicide"
myPal    <- c("forestgreen","chartreuse3","darkolivegreen1")
tDat     <- datComm1 %>% filter(sex=="Total",causeName %in% myCause)
map.1    <- left_join(shape_Comm, tDat, by=c("county","comID")) 




```


```{r}

  tm_shape(map.1) + 
  #tm_facets(by = "causeName", drop.NA.facets = TRUE) +
  tm_layout(frame=F, #scale=1.3,
            main.title= paste(myCause,"Rates in Communities in 2014-2018"),
            #main.title.position = c("center","bottom"),
            attr.outside = TRUE ) + # scale=5
  tm_polygons(col="sig",palette=myPal,style="fixed",breaks=samVec,
              legend.show=T,colorNA="white",
              textNA="Data Suppressed (N < 11)",
              labels = c("Above State Rate (p < 0.05)","Not Stat. Different from State","Below State Rate (p < 0.05)"),title="") 
#  tm_credits("Prepared by: California Department of Public Health (CDPH), Fusion Center; with CDPH Death Data Files, 2013-2017.\nFor more information: https://www.cdph.ca.gov/Programs/CCDPHP/DCDIC/SACB/Pages/ViolencePreventionInitiative.aspx",size=.5,position=c(.40,0))
  
  
#  "Prepared by California Department of Public Health (CDPH) Fusion Center; CDPH Death Data Files, 2013-2017."
  
 
```



```{r}

map.1 <- map.1 %>% filter(county==params$county)

  tm_shape(map.1) + 
  tm_layout(frame=F,scale=1.3,
            main.title= paste(myCause,",",params$county, "2014-2018"),
            #main.title.position = c("center","bottom"),
            attr.outside = TRUE ) + # scale=5
  tm_polygons(col="sig",palette=myPal,style="fixed",breaks=samVec,
              legend.show=T,colorNA="white",
              textNA="Zero",
              labels = c("Above State Rate (p < 0.05)","Not Stat. Different from State","Below State Rate (p < 0.05)"),title="")
 
#  "Prepared by California Department of Public Health (CDPH) Fusion Center; CDPH Death Data Files, 2014-2018."
  
 
```



```{r}
myCause    <- "Firearm-Suicide"
myPal <- c("darkorchid4","mediumorchid3","plum1")
tDat       <- datComm1 %>% filter(sex=="Total",causeName == myCause)
map.1      <- left_join(shape_Comm, datComm1, by=c("county","comID")) 

```


```{r}

  tm_shape(map.1) + 
  tm_layout(frame=F, #scale=1.3,
            main.title= paste(myCause,"Rates in Communities in 2014-2018"),
            #main.title.position = c("center","bottom"),
            attr.outside = TRUE ) + # scale=5
  tm_polygons(col="sig",palette=myPal,style="fixed",breaks=samVec,
              legend.show=T,colorNA="white",
              textNA="Data Suppressed (N < 11)",
              labels = c("Above State Rate (p < 0.05)","Not Stat. Different from State","Below State Rate (p < 0.05)"),title="") 
#  tm_credits("Prepared by: California Department of Public Health (CDPH), Fusion Center; with CDPH Death Data Files, 2013-2017.\nFor more information: https://www.cdph.ca.gov/Programs/CCDPHP/DCDIC/SACB/Pages/ViolencePreventionInitiative.aspx",size=.5,position=c(.40,0))
  
  
#  "Prepared by California Department of Public Health (CDPH) Fusion Center; CDPH Death Data Files, 2013-2017."
  
 
```



```{r}

map.1 <- map.1 %>% filter(county==params$county)

  tm_shape(map.1) + 
  tm_layout(frame=F,scale=1.3,
            main.title= paste(myCause,",",params$county, "2014-2018"),
            #main.title.position = c("center","bottom"),
            attr.outside = TRUE ) + # scale=5
  tm_polygons(col="sig",palette=myPal,style="fixed",breaks=samVec,
              legend.show=T,colorNA="white",
              textNA="Zero",
              labels = c("Above State Rate (p < 0.05)","Not Stat. Different from State","Below State Rate (p < 0.05)"),title="")
 
#  "Prepared by California Department of Public Health (CDPH) Fusion Center; CDPH Death Data Files, 2014-2018."
  
 
```


```{r}
myCounty <- "CALIFORNIA"
tDat <- datCounty_RE %>% filter(causeName %in% c("Firearm-Suicide","Firearm-Homicide"),county == myCounty,yearG3 == "2016-2018", ! raceCode %in% c("Unk-NH","Other-NH"))

ggplot(data=tDat, aes(x=raceCode, y=aRate)) +
   geom_bar(stat="identity",fill="blue") +
   facet_grid(rows = vars(sex),cols = vars(causeName)) +
   theme(axis.text.x = element_text(angle = 90))


ggplot(data=tDat, aes(x=raceCode, y=aRate)) +
   geom_bar(stat="identity",fill="blue") +
   facet_grid(rows = vars(sex),cols = vars(causeName),scales ="free_y" ) +
   theme(axis.text.x = element_text(angle = 90))


ggplot(data=tDat, aes(x=raceCode, y=Ndeaths)) +
   geom_bar(stat="identity",fill="blue") +
   facet_grid(rows = vars(sex),cols = vars(causeName),scales ="free_y" ) +
   theme(axis.text.x = element_text(angle = 90))

```






