---
title: "VP "
author: "Michael Samuel"
always_allow_html: yes
output:
  html_document: default
  word_document: default
---
  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE, message=FALSE)
```


```{r}

#-- Load Packages ------------------------------------------------------------
 library(ggplot2)
 library(dplyr)
 library(tidyr)
 library(readxl)
 library(readr) 
 library(fs)
 library(markdown)

#-- Key Constants -----------------------------------------------------------

 whichData <- "real"
 myPlace   <- "d:/0.CBD/myCBD"
 STATE     <- "CALIFORNIA"
 yearGrp   <- "2013-2017"

 datCounty       <- readRDS(path(myPlace,"/myData/",whichData,"datCounty.RDS"))
 datCounty_RE    <- readRDS(path(myPlace,"/myData/",whichData,"datCounty_RE.RDS"))
 datCounty_3year <- readRDS(path(myPlace,"/myData/",whichData,"datCounty_3year.RDS"))

 
# CHANGE CODES EVERYWHWERE  !!! no -
#         c("White-NH","Black-NH","AIAN-NH","Asian-NH","NHPI-NH", "Multi-NH","Hisp")
tRace <-  c("White-NH","Black-NH",          "Asian-NH",                      "Hisp")

```

```{r}

lghc0 <- filter(datCounty, CAUSE %in% c("E02","E03"))  %>%
           mutate(`Strata`="Sex",Year=as.character(year)) %>% 
           select(CAUSE, Geography=county, Year, `Strata`,
                  `Strata Name`= sex, Numerator=Ndeaths, Denominator=pop, Rate=cDeathRate, aRate, aSE)

lghc1 <- filter(datCounty_RE,CAUSE %in% c("E02","E03"), sex=="Total")  %>%
           mutate(`Strata`="Race/Ethnicity") %>%
           select(CAUSE,Geography=county,Year=yearG3,`Strata`,
                  `Strata Name` = raceCode, Numerator=Ndeaths, Denominator=pop, Rate=cDeathRate, aRate, aSE)

# lghc2 <- filter(datCounty_3year,   CAUSE %in% c("E02","E03"), county != "CALIFORNIA" ) %>%
#            mutate(`Strata`="Sex", Year = yearG3) %>%
#            select(CAUSE,Geography=county,Year=yearG3,`Strata`,
#                   `Strata Name`=sex, Numerator=Ndeaths, Denominator=pop, Rate=cDeathRate, aRate)

lghc2 <- filter(datCounty_3year,   CAUSE %in% c("E02","E03")) %>%
           mutate(`Strata`="Sex", Year = yearG3) %>%
           select(CAUSE,Geography=county,Year=yearG3,`Strata`,
                  `Strata Name`=sex, Numerator=Ndeaths, Denominator=pop, Rate=cDeathRate, aRate, aSE)



lghc3 <- bind_rows(lghc0,lghc1,lghc2) %>%
           mutate(`Strata Name` = ifelse(Strata=="Total","Total",`Strata Name`))


lghcSuicide <- filter(lghc3,CAUSE=="E02") %>%
                mutate(Indicator="Suicide") %>%
                select(Indicator,Geography,Year,Strata,`Strata Name`,Numerator,Denominator,Rate,`Age Adjusted Rate`=aRate)
write_csv(lghcSuicide,"lghcSuicide.csv")


lghcHomicide <- filter(lghc3,CAUSE=="E03") %>%
                mutate(Indicator="Homicide") %>%
                select(Indicator,Geography,Year,Strata,`Strata Name`,Numerator,Denominator,Rate, `Age Adjusted Rate`=aRate, `SE Adjusted Rate`=aSE)
write_csv(lghcHomicide,"lghcHomicide.csv")


```


```{r}
 temp <- lghc2 %>% filter(Geography=="CALIFORNIA",Strata=="Sex") %>%
                  mutate(Year = as.numeric(Year),
                         Cause = ifelse(CAUSE=="E02","Suicide","Homicide"))
```




```{r}
library(ggplot2)
ggplot(temp,aes(x = Year,y = aRate, group=Cause)) +
geom_line(aes(color=Cause), size = 1.5) + 
facet_grid(`Strata Name` ~ .) +
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5))  +
  expand_limits( y = 0) +
  scale_x_continuous(breaks=1990:2017) +
   ggtitle("California Suicide and Homicide Rates by Year and Sex\n (Equal y-axis scale by sex all starting at 0)") 
```


```{r}
library(ggplot2)
ggplot(temp,aes(x = Year,y = aRate, group=Cause)) +
geom_line(aes(color=Cause), size = 1.5) + 
theme(axis.text.x = element_text(angle = 90, vjust = 0.5))  +
  scale_x_continuous(breaks=1990:2017) +   
  facet_grid(`Strata Name` ~ .,scales = "free") +
  ggtitle("California Suicide and Homicide Rates by Year and Sex\n ('Free' y-axis scale)") 


```


```{r }
library(kableExtra)
library(DT)
```

```{r}
sTable <- filter(temp,`Strata Name`=="Total") %>%
           select(Cause,Year,`Number of Deaths`=Numerator,`Age-Adjusted Death Rate`=aRate)
datatable(sTable)
```




