---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(haven)


secure.location  <- "/mnt/projects/CCB/0.Secure.Data/"

```


```{r}

# test  <- read.csv(paste0(secure.location,"rawOSHPD/ED/test.csv") )
# saveRDS(test, file=paste0(secure.location, "myData/TeSt.rds"))


ourVars <- c("dx_prin", "ccs_dx_prin", "patco", "sex", "race_grp",  "agyrserv", "dispn", "payer") 
 
 oshpd.ED.16.0  <- read_sas(paste0(secure.location,"rawOSHPD/ED/cdph_ed_rln2016.sas7bdat") )
 oshpd.ED.16    <- oshpd.ED.16.0  %>% mutate(year=2016) %>% select(ourVars)
 
 saveRDS(oshpd.ED.16, file=paste0(secure.location, "myData/oshpd.ED.16.rds"))


# <!-- oshpd.ED.17.0  <- read_sas(paste0(secure.location,"rawOSHPD/ED/cdph_ed_ssn2017.sas7bdat") )  %>% mutate(year=2017) %>% select(ourVars) -->
# 
# <!-- oshpd.ED.18.0  <- read_sas(paste0(secure.location,"rawOSHPD/ED/cdph_ed_ssn2018.sas7bdat") )  %>% mutate(year=2018) %>% select(ourVars) ## SSN! -->
# 
# 
# 
# <!-- oshpd_ED_subset <- bind_rows(oshpd.ED.16, oshpd.ED.17.0, oshpd.ED.18.0) -->
# 
# 
# 
# <!-- ## TODO could/should standardize all OSHPD names in this step,  eg  countyCode = patco -->
# 
# 
# 
# <!-- saveRDS(oshpd_ED_subset, file=path(secure.location, "myData/oshpd_ED_subset.rds")) -->
# <!-- } -->


```







