---
title: "EDA HD Charges and LOS"
author: "Michael Samuel"
date: "September 11, 2019"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE, message=FALSE)
```

```{r}
#---SET LOCATIONS-----------------------------------------------------------------------

# PROVIDE PATH FOR SECURE DATA HERE
# secure.location  <- "S:/CDCB/Demonstration Folder/Data/OSHPD/PDD/2016/"  # secure location of data
secure.location  <- "e:/0.Secure.Data/"

myDrive <- getwd()  #Root location of CBD project
upPlace <- paste0("d:/0.CBD/myUpstream")

whichData <- "real"   # "real" or "fake"
newData  <- FALSE


#-------------------------------------------------LOAD PACKAGES -----------------------------------------------------------------------------------------------------------------------------------#

library(tidyverse)
library(fs)
library(readxl)
library(summarytools)


#--------------------------------------------------------------------LOAD AND PROCESS OSHPD DATA-----------------------------------------------------------------------------------------#

if (whichData == "real") {
  oshpd16 <- readRDS(file=path(secure.location, "myData/oshpd_subset.rds")) 
}

if (whichData == "fake") {
  oshpd16 <- readRDS(file=path(upPlace, "upData/oshpd16_sample.rds"))
}
```


```{r}


# -MCS exploring summary funtions
# dfSummary(oshpd16)

#summarytools::descr(oshpd16 %>% select(charge,los,los_adj),stats=c("mean","sd","min","q1","med","q3","skewness","n.valid"))

print(descr(oshpd16 %>% select(charge,los,los_adj)), stats=c("mean","sd","min","q1","med","q3","skewness","n.valid"),method = 'render', table.classes = 'st-small')
#descr(oshpd16 %>% select(charge,los,los_adj))

#summarytools::dfSummary(oshpd16)
```


## CHARGES

```{r cars}



#  CHECK CHARGES AND DAYS ======================================================================================
# ==============================================================================================================


# --------------------------------------------------------------------------------------------------------------

charges <- oshpd16$charge

tempCharges  <- table(charges)

# print(freq(oshpd16$charge[oshpd16$charge < 500], method = 'render',table.classes = 'st-small'))


round(100* tempCharges[1:30] / sum(tempCharges) , 6)  
tempCharges[1:30] 

chargesCUT <- charges[charges > 0 & charges <100000]
h1 <- hist(chargesCUT,breaks=1000,main="Charges >0 & <100,000")
h1

chargesCUT <- charges[charges >100000 & charges < 2000000 ]
h2 <- hist(chargesCUT,breaks=1000,main=">100,000 & charges < 2,000,000")
h2

chargesCUT <- charges[charges >2000000 ]
h3 <- hist(chargesCUT,breaks=1000,main=">2,000,000")
h3

# library(cowplot)
# 
# print(plot_grid(h1,h2,h3, labels = "AUTO"))




nMax <- length(tempCharges)
tempCharges[(nMax-30):nMax] 



# OSHPD CHARGE AND CHARGE_PER_TDAY 0 and 1 to NA 
# ospitals that don't report charges (eg Kaiser) are assigned charges of 0, 
# pro bono cases as assigned charges of 1

#------------------LENGTH OF STAY-----------------------------------#

```

## LOS

```{r}

los     <- oshpd16$los
los_adj <- oshpd16$los_adj


tempLOS <- table(los)
round(100* tempLOS[1:35] / sum(tempLOS) , 2)

losCUT <- los_adj[los_adj > 30 & los_adj < 365 ]
hist(losCUT,breaks=1000,main="los  > 30 & <365")


losCUT <- los_adj[los_adj > 365 ]
hist(losCUT,breaks=1000,main="los  > 365")


# oshpd16 %>% filter(los_adj > 100) %>% nrow() #11132 greater than 100 days
# oshpd16 %>% filter(los_adj > 200) %>% nrow() #4074 greater than 200 days
# oshpd16 %>% filter(los_adj > 365) %>% nrow() #2046 greater than 1 year
# oshpd16 %>% filter(los_adj > 1000) %>% nrow() #680 greater than 1000 days
# oshpd16 %>% filter(los_adj > 3650) %>% nrow() #48 greater than 10 years 


#What should the exclusion cut-off be for los_adj? 365 days? Less than that? 

#----------------------------------------------------------------------------------------------------------------------------------------------#
#Some of these extreme los/charges may not even apply to the CAUSE/icdCodes that we're capturing though. Now only looking at values for our CAUSES of interest

```


